reset;

var x1;
var x2;
var x3;
var x4;
var x5;


model;

minimize FO : (x1-1)^2 + (x1-x2)^2 + (x2-x3)^3 + (x3-x4)^4 + (x4-x5)^4;

subject to R1:
  x1 + x2^2 + x3^3 = 2 + 3*sqrt(2);

subject to R2:
  x2 + x4 - x3^2 = -2 + 2*sqrt(2);

subject to R3:
  x1*x5 = 2;

subject to R4:
  -5 <= x1 <= 5;

subject to R5:
  -5 <= x2 <= 5;

subject to R6:
  -5 <= x3 <= 5;

subject to R7:
  -5 <= x4 <= 5;

subject to R8:
  -5 <= x5 <= 5;
  
data;



option solver knitro;

# definição de um ponto inicial para o processo iterativo de solução
let x1 := -100;
let x2 := -100;
let x3 := -100;
let x4 := -100;
let x5 := -100;

solve FO;

display FO;

display x1;
display x2;
display x3;
display x4;
display x5;